Update delete_tags.yml

diff --git a/.github/workflows/delete_tags.yml b/.github/workflows/delete_tags.yml
--- a/.github/workflows/delete_tags.yml
+++ b/.github/workflows/delete_tags.yml
@@ -30,7 +30,7 @@ jobs:
       - name: List and Delete Tags
         run: |
           echo "Fetching tags starting with ${{ github.event.inputs.tag_type }}"
-          tags=$(git tag -l 'dev*' 'qa*' 'qa2*' 'tics*')
+          tags=$(git tag -l 'dev*')
           
           if [ -z "$tags" ]; then
             echo "No tags found starting with '${{ github.event.inputs.tag_type }}'"
@@ -39,6 +39,6 @@ jobs:
 
           for tag in $tags; do
             echo "Deleting tag $tag"
-            #git push --delete origin "$tag" || echo "Failed to delete remote tag $tag"
-            #git tag -d "$tag" || echo "Failed to delete local tag $tag"
+            git push --delete origin "$tag" || echo "Failed to delete remote tag $tag"
+            git tag -d "$tag" || echo "Failed to delete local tag $tag"
           done
